import {
  IHasToolTip,
  TooltipSourceType,
} from "../frontend/src/infrastructure/tooltip";
import { DamageType } from "./damageType";

export enum ItemType {
  NONE = "NONE",
  MELEE = "MELEE",
  RANGED = "RANGED",
  EXPLOSIVE = "EXPLOSIVE",
  MAGIC = "MAGIC",
  CONSUMABLE = "CONSUMABLE",
  TOOL = "TOOL",
  STUFF = "STUFF",
  ARTIFACT = "ARTIFACT",
  HEADGEAR = "HEADGEAR",
  ARMOR = "ARMOR",
  SHIELD = "SHIELD",
  CYBERNETICS = "CYBERNETICS",
  INJURY = "INJURY",
  STRESS = "STRESS",
  ANY = "ANY",
  GOODS = "GOODS",
  AFFLICTION = "AFFLICTION",
  PHYSICAL = "PHYSICAL",
  MENTAL = "MENTAL",
  RELIC = "RELIC",
}

export const physicalItemTypes: ItemType[] = [
  ItemType.MELEE,
  ItemType.RANGED,
  ItemType.EXPLOSIVE,
  ItemType.CONSUMABLE,
  ItemType.TOOL,
  ItemType.STUFF,
  ItemType.ARTIFACT,
  ItemType.HEADGEAR,
  ItemType.ARMOR,
  ItemType.SHIELD,
  ItemType.CYBERNETICS,
  ItemType.INJURY,
  ItemType.GOODS,
  ItemType.RELIC,
];
export const mentalItemTypes: ItemType[] = [
  ItemType.AFFLICTION,
  ItemType.MAGIC,
];
export const unMoveableItems: ItemType[] = [
  ItemType.INJURY,
  ItemType.AFFLICTION,
];
export enum ItemSize {
  SMALL = "SMALL",
  LARGE = "LARGE",
}
export enum StatType {
  QUALITY = "QUALITY",
  DURABILITY = "DURABILITY",
  EFFECT = "EFFECT",
}
export interface IItemStat {
  type: StatType;
  filled?: boolean;
}
export interface IItem extends IHasToolTip {
  name: string;
  type: ItemType;
  stats: StatType[];
  filledSlots?: number;
  damageTypes?: string[];
  hasSkill?: boolean;
  skill?: number;
  size: ItemSize;
  horizontal: boolean;
  image: string;
}

export const itemList: IItem[] = [
  {
    name: "KNIFE",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["CUT", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/knife.jpg",
  },
  {
    name: "CRUDE SPEAR",
    type: ItemType.MELEE,
    stats: [StatType.EFFECT, StatType.QUALITY],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/spear.stone_512.png",
  },
  {
    name: "NUNCHAKU",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/nunchucks.png",
  },
  {
    name: "HARPOON",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/harpoon.png",
  },
  {
    name: "WOODEN CLUB",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/club.png",
  },
  {
    name: "HAMMER",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hammer.png",
  },
  {
    name: "CUTTER",
    type: ItemType.MELEE,
    stats: [StatType.EFFECT, StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cutter.png",
  },
  {
    name: "MACHETE",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/machete.png",
  },
  {
    name: "TORCH",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["LIGHT", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/torch.png",
  },
  {
    name: "LUMBER AXE",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/hatchet.png",
  },
  {
    name: "SHOVEL",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/shovel.png",
  },
  {
    name: "HUGE WRENCH",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/wrench.png",
  },
  {
    name: "SWORD",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/sword.png",
  },
  {
    name: "WHIP",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/whip.png",
  },
  {
    name: "TAZER",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["VOLT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tazer.png",
  },
  {
    name: "GIANT CRUCIFIX",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["LIGHT", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cross.png",
  },
  {
    name: "BOLT STUNNER",
    type: ItemType.MELEE,
    stats: [
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/boltstunner.png",
  },
  {
    name: "MEAT CLEAVER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cleaver.png",
  },
  {
    name: "SCREWDRIVER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/screwdriver.png",
  },
  {
    name: "CROWBAR",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/crowbar.png",
  },
  {
    name: "TIRE IRON",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tireiron.png",
  },
  {
    name: "CLIMBING PICK",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/icepick.png",
  },
  {
    name: "BASEBALL BAT",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bat.png",
  },
  {
    name: "HOCKEY CLUB",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hockey.jpg",
  },
  {
    name: "CHAINSAW",
    type: ItemType.MELEE,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/chainsaw.png",
  },
  {
    name: "CHAINSWORD",
    type: ItemType.MELEE,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/chainsword.png",
  },
  {
    name: "VIBROBLADE",
    type: ItemType.MELEE,
    stats: [
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/vibroblade.png",
  },
  {
    name: "NECRO CLEAVER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/chainaxe.png",
  },
  {
    name: "NECRO BLEEDER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/necrobleeder.png",
  },
  {
    name: "GATOR BLADE",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gatorblade.png",
  },
  {
    name: "POTS AND PANS",
    type: ItemType.MELEE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/potsnpans.png",
  },
  {
    name: "FLASHLIGHT",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/flashlight.png",
  },
  {
    name: "ROPE",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/rope.png",
  },
  {
    name: "CHAIN",
    type: ItemType.MELEE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/grade-30-proof-coil-chain.jpg",
  },
  {
    name: "PORTABLE LADDER",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/ladder.png",
  },
  {
    name: "ARMY KNIFE",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH", "STAB", "CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/swissknife.png",
  },
  {
    name: "2X4",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/2x4Cedarklbs.jpg",
  },
  {
    name: "EXTINGUISHER",
    type: ItemType.MELEE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/extinguisher.png",
  },
  {
    name: "BEAR TRAP",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "CUT", "PAIN", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/beartrap.png",
  },
  {
    name: "BOLT CUTTER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/boltcutter.png",
  },
  {
    name: "PURE STAFF",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/purestaff.png",
  },
  {
    name: "SINISTER STAFF",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/sinisterstaff.png",
  },
  {
    name: "MOP",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/mop.png",
  },
  {
    name: "ROCKET HAMMER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.QUALITY,
    ],
    damageTypes: ["SMASH", "BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/rockethammer.png",
  },
  {
    name: "ROCKET LAUNCHER",
    type: ItemType.MELEE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["", "", "", "", "", "", "", "", "", "", "", "*", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/rpg.png",
  },
  {
    name: "GUITAR",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY],
    damageTypes: ["", "", "", "*", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/guitar.png",
  },
  {
    name: "CROSSBOW",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/crossbow.png",
  },
  {
    name: "GATOR BOWGUN",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gator-bowgun.png",
  },
  {
    name: "WRIST CANNON",
    type: ItemType.RANGED,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/slingshot.png",
  },
  {
    name: "THROWING KNIVES",
    type: ItemType.RANGED,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/knives.png",
  },
  {
    name: "COMPOUND BOW",
    type: ItemType.RANGED,
    stats: [StatType.EFFECT, StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bow.png",
  },
  {
    name: "MAKESHIFT PISTOL",
    type: ItemType.RANGED,
    stats: [StatType.EFFECT, StatType.EFFECT, StatType.QUALITY],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/makeshiftpistol.png",
  },
  {
    name: "PIPE GUN",
    type: ItemType.RANGED,
    stats: [StatType.EFFECT, StatType.QUALITY],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/pipegun.png",
  },
  {
    name: "BERETTA",
    type: ItemType.RANGED,
    stats: [StatType.EFFECT, StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/beretta.png",
  },
  {
    name: "MAGNUM",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
    ],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/magnus.png",
  },
  {
    name: "HAND CANNON",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/handcannon.png",
  },
  {
    name: "SHOTGUN",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/shotgun.png",
  },
  {
    name: "WINCHESTER",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/winchester.png",
  },
  {
    name: "TEC 9",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tec9.png",
  },
  {
    name: "SCORPION",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/scorpion.png",
  },
  {
    name: "M-16",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/m16.png",
  },
  {
    name: "AK47",
    type: ItemType.RANGED,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/ak47.png",
  },
  {
    name: "M29-LMG",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/PEO_M249_Para_ACOG.jpg",
  },
  {
    name: "AUTOCANNON",
    type: ItemType.RANGED,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "PAIN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/Autocannon_Vraks.png",
  },
  {
    name: "MEGIDDO MORTAR",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["BLAST", "LIGHT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/megiddo.png",
  },
  {
    name: "NAILGUN",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["PAIN", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image:
      "img/items/nailgun_01.png14672430-033D-4D2C-858B-E5B447482AF8Large-removebg-preview.png",
  },
  {
    name: "DART GUN",
    type: ItemType.RANGED,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["*","","","","","",""],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: true,
    image:
      "img/items/dartgun.png",
  },
  {
    name: "NECRO RIFLE",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/hellrifle.png",
  },
  {
    name: "NECRO REPEATER",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "STAB", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/necrorepeater.png",
  },
  {
    name: "BEAR ARBALEST",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["PAIN", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/bearbalest.png",
  },
  {
    name: "FRAG GRENADE",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["PAIN", "BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/grenade.png",
  },
  {
    name: "FLASHBANG",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["*", "BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/flashbang.png",
  },
  {
    name: "MOLOTOV COCKTAIL",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["*", "LIGHT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/molotov.png",
  },
  {
    name: "TANK SHELL",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/tankshell.png",
  },
  {
    name: "DYNAMITE",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/explosives.png",
  },
  {
    name: "BOLT",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["VOLT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bolt.png",
  },
  {
    name: "SHOCKWAVE",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["VOLT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/shockwave.png",
  },
  {
    name: "MAGNETIZE",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["VOLT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/magnetism.png",
  },
  {
    name: "ANEURYSM",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["NEURAL"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/brainbleed.png",
  },
  {
    name: "VOICES",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["NEURAL"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/voices.png",
  },
  {
    name: "CONFUSION",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["NEURAL"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/autism.png",
  },
  {
    name: "VILE MUTAGEN",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["OOZE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cancer-delande-celler-iStock-removebg-preview.png",
  },
  {
    name: "FUNGAL GROWTH",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["OOZE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/fungus.png",
  },
  {
    name: "EXPUNGE",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["OOZE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/expunge.png",
  },
  {
    name: "ENFLAME",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["LIGHT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/enflame.png",
  },
  {
    name: "EXPLOSION",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["LIGHT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/explosion.png",
  },
  {
    name: "ADRENALINE",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["LIGHT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/strength.png",
  },
  {
    name: "IRRADIATE",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["NUKE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/Plutonium_pellet-removebg-preview.png",
  },
  {
    name: "MELT",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["NUKE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/melt.png",
  },
  {
    name: "GRAVITY",
    type: ItemType.MAGIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["NUKE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gravity.png",
  },
  {
    name: "RATIONS",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/rations.png",
  },
  {
    name: "FRESH FRUITS",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/frutas_4-removebg-preview.png",
  },
  {
    name: "WATER",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/aqua.jpg",
  },
  {
    name: "CAPRISUN",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/caprisun.jpg",
  },
  {
    name: "NAILS",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/nails.png",
  },
  {
    name: "ADHESIVE",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/adhesive.png",
  },
  {
    name: "TAPE",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tape.png",
  },
  {
    name: "COPPER WIRE",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/copperwire.png",
  },
  {
    name: "COSMETICS",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/makeup.png",
  },
  {
    name: "SENSORS",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/sensors.png",
  },
  {
    name: "TIMER",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/timer.png",
  },
  {
    name: "REMOTE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/remote.png",
  },
  {
    name: "CAMERA",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/camera.png",
  },
  {
    name: "WALKIE TALKIE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/shortrangeradio.png",
  },
  {
    name: "MEDICINE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/meds.png",
  },
  {
    name: "FIRST AID KIT",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/aidkit.png",
  },
  {
    name: "INFLATABLE BOAT",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/boat.png",
  },
  {
    name: "CAR BATTERY",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/carbattery.png",
  },
  {
    name: "CIGARETTES",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cigarettes.png",
  },
  {
    name: "MATCHES",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/matches.png",
  },
  {
    name: "GASOLINE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gasoline.png",
  },
  {
    name: "CAR PARTS",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/carparts.png",
  },
  {
    name: "GEIGER COUNTER",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/geiger.jpg",
  },
  {
    name: "PORTABLE STILL",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/still.jpg",
  },
  {
    name: "TENT",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tent.jpg",
  },
  {
    name: "VIALS",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/vials.png",
  },
  {
    name: "ACID",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/acid.png",
  },
  {
    name: "CHEMICALS",
    type: ItemType.STUFF,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/ricca-solvents-removebg-preview.png",
  },
  {
    name: "PARACHUTE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/download.jpg",
  },
  {
    name: "OFFICE SUPPLIES",
    type: ItemType.STUFF,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/office.png",
  },
  {
    name: "CHEWING GUM",
    type: ItemType.STUFF,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/chewinggum.png",
  },
  {
    name: "BUCKET",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bucket.png",
  },
  {
    name: "STEAK",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/Ribeye_Steak_Lip-on-removebg-preview.png",
  },
  {
    name: "WATER DISPENSER",
    type: ItemType.CONSUMABLE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/water.png",
  },
  {
    name: "PAPER MONEY",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/history-of-paper-money-removebg-preview.png",
  },
  {
    name: "REGENERATIUM",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/syringe.medical_512-removebg-preview.png",
  },
  {
    name: "AMPHETAMINES",
    type: ItemType.TOOL,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/amphetamine.png",
  },
  {
    name: "HALLUCINOGENS",
    type: ItemType.TOOL,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/lsd.png",
  },
  {
    name: "OPIOIDS",
    type: ItemType.TOOL,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/Opium-100glas-removebg-preview.png",
  },
  {
    name: "BOOZE",
    type: ItemType.CONSUMABLE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bottle-of-booze-700-189084535-removebg-preview.png",
  },
  {
    name: "AMMO",
    type: ItemType.STUFF,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/ammo.png",
  },
  {
    name: "BINOCULARS",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/binoculars.png",
  },
  {
    name: "BURNER GENERATOR",
    type: ItemType.TOOL,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/generator.png",
  },
  {
    name: "IRON",
    type: ItemType.GOODS,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.EFFECT],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/iron.png",
  },
  {
    name: "GOLD",
    type: ItemType.GOODS,
    stats: [
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gold.png",
  },
  {
    name: "SALT",
    type: ItemType.GOODS,
    stats: [StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/salt.png",
  },
  {
    name: "HOCKEY MASK",
    type: ItemType.HEADGEAR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hocketmask.png",
  },
  {
    name: "ROAD HELMET",
    type: ItemType.HEADGEAR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/motorbikehelmet.png",
  },
  {
    name: "BIKE HELMET",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bikehelmet.jpg",
  },
  {
    name: "HARDHAT",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hardhat.jpg",
  },
  {
    name: "GAS MASK",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["OOZE"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gasmask.jpg",
  },
  {
    name: "GOGGLES",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/goggles.png",
  },
  {
    name: "SKULL HELMET",
    type: ItemType.HEADGEAR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["PAIN"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/skull.png",
  },
  {
    name: "TINFOIL HAT",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY],
    damageTypes: ["NEURAL"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tinfoilhat.png",
  },
  {
    name: "KEVLAR VEST",
    type: ItemType.ARMOR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["GUN"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/kevlar.jpg",
  },
  {
    name: "GRAPHITE VEST",
    type: ItemType.ARMOR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["STAB"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/kevlar.jpg",
  },
  {
    name: "HOCKEY ARMOR",
    type: ItemType.ARMOR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hockeyarmor.png",
  },
  {
    name: "LEATHER VEST",
    type: ItemType.ARMOR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["PAIN"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/leather.png",
  },
  {
    name: "METAL PLATE",
    type: ItemType.ARMOR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["CUT"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/metalplate-removebg-preview.png",
  },
  {
    name: "RIOT SHIELD",
    type: ItemType.SHIELD,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["BLAST"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/riotshield.png",
  },
  {
    name: "STOP SIGN",
    type: ItemType.SHIELD,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["STAB"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/stopshield.jpg",
  },
  {
    name: "PLANKS WITH GRIP",
    type: ItemType.SHIELD,
    stats: [StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["VOLT"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/plank.png",
  },
  {
    name: "MARINE ARMOR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["BURST", "BLAST"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/armor-combat.png",
  },
  {
    name: "COMBAT ARMOR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["NUKE", "LIGHT"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/combat-armor.png",
  },
  {
    name: "BULL ARMOR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["OOZE", "NEURAL"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/poweredarmor.jpg",
  },
  {
    name: "SHELL ARMOR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "LIGHT"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/shellarmor.png",
  },
  {
    name: "HAZMAT SUIT",
    type: ItemType.ARMOR,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "OOZE", "NUKE", "VOLT"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/hazmat.png",
  },
  {
    name: "CAMOUFLAGE",
    type: ItemType.ARMOR,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "PAIN"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image:
      "img/items/kamouflage-och-maskering-ghillie-suit-woodland-44574-f1-removebg-preview.png",
  },
  {
    name: "ARCTIC GEAR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["*", "CUT", "SMASH"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/arctic.png",
  },
  {
    name: "GRAPPLER",
    type: ItemType.CYBERNETICS,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT", "PAIN", "SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/grapplehand.png",
  },
  {
    name: "BIONIC ARM",
    type: ItemType.CYBERNETICS,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["PAIN", "SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bionicarm.png",
  },
  {
    name: "BIONIC LEG",
    type: ItemType.CYBERNETICS,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bionicleg.png",
  },
  {
    name: "BIONIC EYE",
    type: ItemType.CYBERNETICS,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bioniceye.png",
  },
  {
    name: "POLYGEL",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/polygel.png",
  },
  {
    name: "BIO-SCANNER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bio-scanner.png",
  },
  {
    name: "NEURO-ANIMATOR",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/neuro-animator.png",
  },
  {
    name: "GATE RECOILER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/teleport-thumb-1.jpg",
  },
  {
    name: "X-RAY BEAM",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/x-ray.png",
  },
  {
    name: "SOLAR CONDENSER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/solarcondenser.png",
  },
  {
    name: "ROCKET SKATES",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/rocketskates.png",
  },
  {
    name: "FOAMCRETE DISPENSER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/foamgel.png",
  },
  {
    name: "2-DIMENSIONAL SUIT",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/2d.png",
  },
  {
    name: "MAG BOOTS",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/magboots.png",
  },
  {
    name: "ANTI-GRAV BOOTS",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/antigrav.png",
  },
  {
    name: "COPTER PACK",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/copterpack.png",
  },
  {
    name: "GROWGEL INJECTOR",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/growgel.png",
  },
  {
    name: "SLAVE CROWN",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/slavecrown.png",
  },
  {
    name: "LASER SCULPTER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/lasersculpter.png",
  },
  {
    name: "THERMOBARIC CELL",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/thermobariccell.png",
  },
  {
    name: "AUTODOC",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/autodoc.png",
  },
  {
    name: "LIFEFORM SENSOR",
    type: ItemType.ARTIFACT,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/lifeformsensor.png",
  },
  {
    name: "EXPANDABLE SOLAR",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/solar.png",
  },
  {
    name: "EXPANDABLE TURBINE",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/windturbine.png",
  },
  {
    name: "ETHER SPEAR",
    type: ItemType.RELIC,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["", "", "", DamageType.STAB, DamageType.VOLT],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/ether-spear.png",
    tooltipText:
      "The Ether Spear phases through the physical plane as it is thrown. Using a tactical action the Ether spear can be commanded to hit a specific target in vision. Until the end of combat, or until commanded otherwise, the spear will always hit the same target. When attacking with the Ether Spear, the wielder can spend a volt magic charge to roll with advantage. The Ether Spear returns to its wielders hand after being thrown.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "THE ISOTOPE",
    type: ItemType.RELIC,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [DamageType.CUT, DamageType.NUKE, DamageType.SMASH],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/the-isotope.png",
    tooltipText:
      "The Isotope can be commanded to glow in a green light, giving off a bright light reaching up to 20 meters. Dealing critical damage with The Isotope causes the target to be knocked back one tile. Also, when attacking with The Isotope, the wielder can spend a nuke magic charge to roll with advantage.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "LIVING FLAME",
    type: ItemType.RELIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/living-fire.png",
    tooltipText:
      "A locket containing sentient fire. Using the Living fire pendant costs a point of durability, a point of durability regenerates if spending a unit of downtime on recharging the pendant. When opened, the pendant does a choice of the following; Illuminate 100 cubic meters in radiant light. Cauterize a fresh infection, treating it and filling two slots. As a tactical action, deals 2d6 light damage at any range, and on failed STR the victim cannot attack during the first turn.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "OOZEKEEPER",
    type: ItemType.RELIC,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [
      DamageType.OOZE,
      "",
      "",
      "",
      "",
      "",
    ],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/oozekeeper.png",
    tooltipText: "The Oozekeeper sprays short bursts of pressurized ooze at high velocity. Oozekeeper ignores armovr completely. As a tactical action, the wielder may create a pool of ooze at any one tile. Anyone starting their turn on this tile suffers 1d6 ooze damage, which ignores armor.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "STATIC",
    type: ItemType.RELIC,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [
      DamageType.VOLT,
      DamageType.NUKE,
      DamageType.OOZE,
      DamageType.LIGHT,
      DamageType.NEURAL,
    ],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/static-plate.png",
    tooltipText: "A plate infused with volt powers, granting protection against all magic. When the wearer would take volt damage, they instead make a STR save with advantage, on take damage only if it fails.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "GUNDAM SUIT",
    type: ItemType.RELIC,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.QUALITY,
    ],
    damageTypes: [
      DamageType.CUT,
      DamageType.GUN,
      DamageType.STAB,
      DamageType.SMASH,
      DamageType.BURST,
      DamageType.BLAST,
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/gundam-suit.png",
    tooltipText: "A gundam mobile suit fit for a human. As a tactical action, or out of combat, the Gundam suit can be powered for 5 minutes by spending a volt magic charge. While powered, the Gundam suit can fly at a speed up to 150km/h.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "FLASHMELTER",
    type: ItemType.RELIC,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [
      DamageType.NUKE,
      DamageType.PAIN,
    ],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/fleshmelter.png",
    tooltipText: "A beam of radiation melting skin and flesh. The Flashmelter can be overcharged using a tactical action and by spending a durability. When overcharged, it deals its damage, and skill die as splash damage.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "PRESERVED VESSEL",
    type: ItemType.RELIC,
    stats: [
      StatType.DURABILITY,
    ],
    damageTypes: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/preservedvessel.png",
    tooltipText: "A preserved vessel is a powerful neural relic, which may move the mind of a sentient creature into it, and then discharge this mind into a new, similar, mindless body. The procedure to store a mind is instant, but requires all remaining charges of a neural spell, and can be performed on someone who died the last 5 seconds. While stored, the mind is confused, but able to speak through the preserved vessel. When discharged, the mind enters its new body, and the vessel crumbles.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "THE TEAMMATE",
    type: ItemType.RELIC,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [
      DamageType.NEURAL,
      DamageType.VOLT,
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/headset.png",
    tooltipText: "The Teammate, when worn as a helmet can be attuned to another willing creature by the wearer spending a neural, or volt magic charge and a timeslot for both wearer and target. While attuned, the wearer and the target can communicate telepathically, over any distances. If the wearer removes the helmet the attunement is forfeit. If any of the linked creatures die while attuned, the other one suffers a madness.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "POP POP",
    type: ItemType.RELIC,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [
      DamageType.GUN,
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/goldengun.png",
    tooltipText: "Pop pop can shoot multiple bullets. By using a tactical action Pop pop goes brrrap, and attacks twice, but can only fire every third turn.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "ORM THE URN",
    type: ItemType.RELIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/urn.png",
    tooltipText: "Orm is an urn, sentient by use of neural magic. Orm is friendly, adventurous, but greedy. Orm is stealthy, and very fast for being an urn, and moves as fast as any human or mutant. He can carry up to one litre of water, or equivalent in size, he does not corrode or melt, but might be dented or broken. For proper payment, or for a friend, Orm will carry, or deliver things.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "UNIVERSAL REMOTE",
    type: ItemType.RELIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/the-universal.png",
    tooltipText: "The universal is an ancient, state of the art remote, which can issue one of its four commands to any hardware with a reciever, but fragile as it is it suffers one point of damage when doing so. The commands are; Shutdown, self-destruct, factory restore, and overclock.",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "GEM DIMENSION 4",
    type: ItemType.RELIC,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/relics/4d-gem.png",
    tooltipText: "The Gem dimension 4 is a magical artifact of unknown origin. It is used by spending a tactical action and one of its 3 durability. When used, the gem first stores the users state, and can then be used again for no durability cost, within 30 minutes, to restore their position and bodily state, moving the user back to that position, and restoring their state of injury back to what it was. If the Gem passes to another creatures possesion, it loses any stored information. The Gem cannot be repaired, but only recharged by spending 1 point of experience and a time slot",
    tooltipSource: TooltipSourceType.TEXT,
  },
  {
    name: "BUSTED RIBCAGE",
    type: ItemType.INJURY,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/ribcage.png",
  },
  {
    name: "CRACKED KNEE",
    type: ItemType.INJURY,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/crackedknee.png",
  },
  {
    name: "KEFF AXEL",
    type: ItemType.INJURY,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/shoulder.png",
  },
  {
    name: "POISONED",
    type: ItemType.INJURY,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/poison.png",
  },
  {
    name: "SICKNESS",
    type: ItemType.INJURY,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/virus.png",
  },
  {
    name: "INFECTION",
    type: ItemType.INJURY,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/infection.png",
  },
  {
    name: "DRAINED",
    type: ItemType.AFFLICTION,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/drained.png",
  },
  {
    name: "DRUGGED",
    type: ItemType.AFFLICTION,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/drugged.png",
  },
  {
    name: "MUTATION",
    type: ItemType.AFFLICTION,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/tumor.png",
  },
  {
    name: "MADNESS",
    type: ItemType.AFFLICTION,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/injury/madness.png",
  },
];
