import { IRollable, RollableHandler } from "./../shared/random";
import { ISelectable } from "../frontend/src/infrastructure/selection";
import { DiceType } from "../contracts/models/dice";
import { IHasStats } from "../contracts/stats";

export enum ItemType {
  MELEE = "MELEE",
  RANGED = "RANGED",
  EXPLOSIVE = "EXPLOSIVE",
  MAGIC = "MAGIC",
  CONSUMABLE = "CONSUMABLE",
  TOOL = "TOOL",
  STUFF = "STUFF",
  ARTIFACT = "ARTIFACT",
  HEADGEAR = "HEADGEAR",
  ARMOR = "ARMOR",
  SHIELD = "SHIELD",
  CYBERNETICS = "CYBERNETICS",
  ANY = "ANY",
}
export enum ItemSize {
  SMALL = "SMALL",
  LARGE = "LARGE",
}
export enum StatType {
  QUALITY = "QUALITY",
  DURABILITY = "DURABILITY",
  EFFECT = "EFFECT",
}
export interface IItemStat {
  type: StatType;
  filled?: boolean;
}
export interface IItem {
  name: string;
  type: ItemType;
  stats: StatType[];
  filledSlots?: number[];
  damageTypes?: string[];
  hasSkill?: boolean;
  skill?: number;
  size: ItemSize;
  horizontal: boolean;
  image: string;
}
export class OwnedItem implements IItem, ISelectable, IRollable {
  name: string;
  type: ItemType;
  stats: StatType[];
  filledSlots?: number[];
  damageTypes?: string[];
  hasSkill?: boolean;
  skill?: number;
  size: ItemSize;
  horizontal: boolean;
  image: string;
  isSelected: boolean;
  selectionGroup: string;
  owner: IHasStats | undefined;
  constructor(item: IItem | undefined, owner: IHasStats | undefined = undefined) {
    if(item == undefined) return;
    Object.assign(this, item);
    this.owner = owner;
  }
  getBaseDice(rollableHandler: RollableHandler | null): DiceType[] {
    const result: DiceType[] = [];
    if(!rollableHandler) return result;
    if (this.hasSkill && this.skill) {
      result.push(rollableHandler.numberToDieType(this.skill));
    }
    if (this.owner) {
      result.push(rollableHandler.numberToDieType(this.owner.level));
    }
    let diceType: DiceType = DiceType.NONE;
    
    this.stats.forEach((statType, index) => {
      if (statType == StatType.DURABILITY) return;
      if (statType == StatType.EFFECT){
        diceType = rollableHandler.advanceDiceType(diceType);
        return;
      }
      if (!this.filledSlots) {
        diceType = rollableHandler.advanceDiceType(diceType);
        return;
      }
      if(this.filledSlots.indexOf(index) != -1) return;
      diceType = rollableHandler.advanceDiceType(diceType);
    });
    result.push(diceType);
    return result;
  }
}
export interface ISelectableItem extends IItem, ISelectable {}
export const itemList: IItem[] = [
  {
    name: "KNIFE",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["CUT", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/knife.jpg",
  },
  {
    name: "CRUDE SPEAR",
    type: ItemType.MELEE,
    stats: [StatType.EFFECT, StatType.QUALITY],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/spear.stone_512.png",
  },
  {
    name: "NUNCHAKU",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/nunchucks.png",
  },
  {
    name: "HARPOON",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/harpoon.png",
  },
  {
    name: "WOODEN CLUB",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/club.png",
  },
  {
    name: "HAMMER",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hammer.png",
  },
  {
    name: "CUTTER",
    type: ItemType.MELEE,
    stats: [StatType.EFFECT, StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cutter.png",
  },
  {
    name: "MACHETE",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/machete.png",
  },
  {
    name: "TORCH",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["LIGHT", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/torch.png",
  },
  {
    name: "LUMBER AXE",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/hatchet.png",
  },
  {
    name: "SHOVEL",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/shovel.png",
  },
  {
    name: "HUGE WRENCH",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/wrench.png",
  },
  {
    name: "SWORD",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/sword.png",
  },
  {
    name: "WHIP",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/whip.png",
  },
  {
    name: "TAZER",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["VOLT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tazer.png",
  },
  {
    name: "GIANT CRUCIFIX",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["LIGHT", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cross.png",
  },
  {
    name: "BOLT STUNNER",
    type: ItemType.MELEE,
    stats: [
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/boltstunner.png",
  },
  {
    name: "MEAT CLEAVER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cleaver.png",
  },
  {
    name: "SCREWDRIVER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/screwdriver.png",
  },
  {
    name: "CROWBAR",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/crowbar.png",
  },
  {
    name: "TIRE IRON",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tireiron.png",
  },
  {
    name: "CLIMBING PICK",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/icepick.png",
  },
  {
    name: "BASEBALL BAT",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bat.png",
  },
  {
    name: "HOCKEY CLUB",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hockey.jpg",
  },
  {
    name: "CHAINSAW",
    type: ItemType.MELEE,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/chainsaw.png",
  },
  {
    name: "CHAINSWORD",
    type: ItemType.MELEE,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/chainsword.png",
  },
  {
    name: "VIBROBLADE",
    type: ItemType.MELEE,
    stats: [
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/vibroblade.png",
  },
  {
    name: "NECRO CLEAVER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/chainaxe.png",
  },
  {
    name: "NECRO BLEEDER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/necrobleeder.png",
  },
  {
    name: "GATOR BLADE",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["CUT", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gatorblade.png",
  },
  {
    name: "POTS AND PANS",
    type: ItemType.MELEE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/potsnpans.png",
  },
  {
    name: "FLASHLIGHT",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/flashlight.png",
  },
  {
    name: "ROPE",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/rope.png",
  },
  {
    name: "CHAIN",
    type: ItemType.MELEE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/grade-30-proof-coil-chain.jpg",
  },
  {
    name: "PORTABLE LADDER",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/ladder.png",
  },
  {
    name: "ARMY KNIFE",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH", "STAB", "CUT", "PAIN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/swissknife.png",
  },
  {
    name: "2X4",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/2x4Cedarklbs.jpg",
  },
  {
    name: "EXTINGUISHER",
    type: ItemType.MELEE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/extinguisher.png",
  },
  {
    name: "BEAR TRAP",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "CUT", "PAIN", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/beartrap.png",
  },
  {
    name: "BOLT CUTTER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/boltcutter.png",
  },
  {
    name: "PURE STAFF",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/purestaff.png",
  },
  {
    name: "SINISTER STAFF",
    type: ItemType.MELEE,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/sinisterstaff.png",
  },
  {
    name: "MOP",
    type: ItemType.MELEE,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/mop.png",
  },
  {
    name: "ROCKET HAMMER",
    type: ItemType.MELEE,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.QUALITY,
    ],
    damageTypes: ["SMASH", "BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/rockethammer.png",
  },
  {
    name: "CROSSBOW",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/crossbow.png",
  },
  {
    name: "GATOR BOWGUN",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB", "SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gator-bowgun.png",
  },
  {
    name: "WRIST CANNON",
    type: ItemType.RANGED,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/slingshot.png",
  },
  {
    name: "THROWING KNIVES",
    type: ItemType.RANGED,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/knives.png",
  },
  {
    name: "COMPOUND BOW",
    type: ItemType.RANGED,
    stats: [StatType.EFFECT, StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bow.png",
  },
  {
    name: "MAKESHIFT PISTOL",
    type: ItemType.RANGED,
    stats: [StatType.EFFECT, StatType.EFFECT, StatType.QUALITY],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/makeshiftpistol.png",
  },
  {
    name: "PIPE GUN",
    type: ItemType.RANGED,
    stats: [StatType.EFFECT, StatType.QUALITY],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/pipegun.png",
  },
  {
    name: "BERETTA",
    type: ItemType.RANGED,
    stats: [StatType.EFFECT, StatType.QUALITY, StatType.QUALITY],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/beretta.png",
  },
  {
    name: "MAGNUM",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
    ],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/magnus.png",
  },
  {
    name: "HAND CANNON",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/handcannon.png",
  },
  {
    name: "SHOTGUN",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/shotgun.png",
  },
  {
    name: "WINCHESTER",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/winchester.png",
  },
  {
    name: "TEC 9",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tec9.png",
  },
  {
    name: "SCORPION",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/scorpion.png",
  },
  {
    name: "M-16",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/m16.png",
  },
  {
    name: "AK47",
    type: ItemType.RANGED,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/ak47.png",
  },
  {
    name: "M29-LMG",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.QUALITY,
      StatType.QUALITY,
    ],
    damageTypes: ["BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/PEO_M249_Para_ACOG.jpg",
  },
  {
    name: "AUTOCANNON",
    type: ItemType.RANGED,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "PAIN", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/Autocannon_Vraks.png",
  },
  {
    name: "MEGIDDO MORTAR",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["BLAST", "LIGHT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/megiddo.png",
  },
  {
    name: "NAILGUN",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["PAIN", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image:
      "img/items/nailgun_01.png14672430-033D-4D2C-858B-E5B447482AF8Large-removebg-preview.png",
  },
  {
    name: "NECRO RIFLE",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/hellrifle.png",
  },
  {
    name: "NECRO REPEATER",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "STAB", "BURST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/necrorepeater.png",
  },
  {
    name: "BEAR ARBALEST",
    type: ItemType.RANGED,
    stats: [
      StatType.EFFECT,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["PAIN", "STAB"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/bearbalest.png",
  },
  {
    name: "FRAG GRENADE",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["PAIN", "BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/grenade.png",
  },
  {
    name: "FLASHBANG",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["*", "BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/flashbang.png",
  },
  {
    name: "MOLOTOV COCKTAIL",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["*", "LIGHT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/molotov.png",
  },
  {
    name: "TANK SHELL",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/tankshell.png",
  },
  {
    name: "DYNAMITE",
    type: ItemType.EXPLOSIVE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
      StatType.EFFECT,
    ],
    damageTypes: ["BLAST"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/explosives.png",
  },
  {
    name: "BOLT",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["VOLT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bolt.png",
  },
  {
    name: "SHOCKWAVE",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["VOLT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/shockwave.png",
  },
  {
    name: "ANEURYSM",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["NEURAL"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/brainbleed.png",
  },
  {
    name: "VOICES",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["NEURAL"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/voices.png",
  },
  {
    name: "AUTISM",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["NEURAL"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/autism.png",
  },
  {
    name: "VILE MUTAGEN",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["OOZE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cancer-delande-celler-iStock-removebg-preview.png",
  },
  {
    name: "FUNGAL GROWTH",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["OOZE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/fungus.png",
  },
  {
    name: "ENFLAME",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["LIGHT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/enflame.png",
  },
  {
    name: "EXPLOSION",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["LIGHT"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/explosion.png",
  },
  {
    name: "IRRADIATE",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["NUKE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/Plutonium_pellet-removebg-preview.png",
  },
  {
    name: "MELT",
    type: ItemType.MAGIC,
    stats: [],
    damageTypes: ["NUKE"],
    hasSkill: true,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/melt.png",
  },
  {
    name: "RATIONS",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/rations.png",
  },
  {
    name: "FRESH FRUITS",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/frutas_4-removebg-preview.png",
  },
  {
    name: "WATER",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/aqua.jpg",
  },
  {
    name: "CAPRISUN",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/caprisun.jpg",
  },
  {
    name: "NAILS",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/nails.png",
  },
  {
    name: "ADHESIVE",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/adhesive.png",
  },
  {
    name: "TAPE",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tape.png",
  },
  {
    name: "COPPER WIRE",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/copperwire.png",
  },
  {
    name: "COSMETICS",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/makeup.png",
  },
  {
    name: "SENSORS",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/sensors.png",
  },
  {
    name: "TIMER",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/timer.png",
  },
  {
    name: "REMOTE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/remote.png",
  },
  {
    name: "CAMERA",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/camera.png",
  },
  {
    name: "WALKIE TALKIE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/shortrangeradio.png",
  },
  {
    name: "MEDICINE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/meds.png",
  },
  {
    name: "FIRST AID KIT",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/aidkit.png",
  },
  {
    name: "INFLATABLE BOAT",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/boat.png",
  },
  {
    name: "CAR BATTERY",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/carbattery.png",
  },
  {
    name: "CIGARETTES",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/cigarettes.png",
  },
  {
    name: "MATCHES",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/matches.png",
  },
  {
    name: "GASOLINE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gasoline.png",
  },
  {
    name: "CAR PARTS",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/carparts.png",
  },
  {
    name: "GEIGER COUNTER",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/geiger.jpg",
  },
  {
    name: "PORTABLE STILL",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/still.jpg",
  },
  {
    name: "TENT",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tent.jpg",
  },
  {
    name: "VIALS",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/vials.png",
  },
  {
    name: "ACID",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/acid.png",
  },
  {
    name: "CHEMICALS",
    type: ItemType.STUFF,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/ricca-solvents-removebg-preview.png",
  },
  {
    name: "PARACHUTE",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/download.jpg",
  },
  {
    name: "OFFICE SUPPLIES",
    type: ItemType.STUFF,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/office.png",
  },
  {
    name: "CHEWING GUM",
    type: ItemType.STUFF,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/chewinggum.png",
  },
  {
    name: "BUCKET",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bucket.png",
  },
  {
    name: "STEAK",
    type: ItemType.CONSUMABLE,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/Ribeye_Steak_Lip-on-removebg-preview.png",
  },
  {
    name: "WATER DISPENSER",
    type: ItemType.CONSUMABLE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/water.png",
  },
  {
    name: "PAPER MONEY",
    type: ItemType.STUFF,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/history-of-paper-money-removebg-preview.png",
  },
  {
    name: "REGENERATIUM",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/syringe.medical_512-removebg-preview.png",
  },
  {
    name: "AMPHETAMINES",
    type: ItemType.TOOL,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/amphetamine.png",
  },
  {
    name: "HALLUCINOGENS",
    type: ItemType.TOOL,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/lsd.png",
  },
  {
    name: "OPIOIDS",
    type: ItemType.TOOL,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/Opium-100glas-removebg-preview.png",
  },
  {
    name: "BOOZE",
    type: ItemType.CONSUMABLE,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bottle-of-booze-700-189084535-removebg-preview.png",
  },
  {
    name: "AMMO",
    type: ItemType.STUFF,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/ammo.png",
  },
  {
    name: "BINOCULARS",
    type: ItemType.TOOL,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/binoculars.png",
  },
  {
    name: "EXPANDABLE SOLAR",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/solar.png",
  },
  {
    name: "EXPANDABLE TURBINE",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/windturbine.png",
  },
  {
    name: "BURNER GENERATOR",
    type: ItemType.TOOL,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/generator.png",
  },
  {
    name: "HOCKEY MASK",
    type: ItemType.HEADGEAR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hocketmask.png",
  },
  {
    name: "ROAD HELMET",
    type: ItemType.HEADGEAR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/motorbikehelmet.png",
  },
  {
    name: "BIKE HELMET",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bikehelmet.jpg",
  },
  {
    name: "HARDHAT",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hardhat.jpg",
  },
  {
    name: "GAS MASK",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["OOZE"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/gasmask.jpg",
  },
  {
    name: "GOGGLES",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/goggles.png",
  },
  {
    name: "SKULL HELMET",
    type: ItemType.HEADGEAR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["PAIN"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/skull.png",
  },
  {
    name: "TINFOIL HAT",
    type: ItemType.HEADGEAR,
    stats: [StatType.DURABILITY],
    damageTypes: ["NEURAL"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/tinfoilhat.png",
  },
  {
    name: "KEVLAR VEST",
    type: ItemType.ARMOR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["GUN"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/kevlar.jpg",
  },
  {
    name: "HOCKEY ARMOR",
    type: ItemType.ARMOR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/hockeyarmor.png",
  },
  {
    name: "LEATHER VEST",
    type: ItemType.ARMOR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["PAIN"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/leather.png",
  },
  {
    name: "METAL PLATE",
    type: ItemType.ARMOR,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["CUT"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/metalplate-removebg-preview.png",
  },
  {
    name: "RIOT SHIELD",
    type: ItemType.SHIELD,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["BLAST"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/riotshield.png",
  },
  {
    name: "STOP SIGN",
    type: ItemType.SHIELD,
    stats: [StatType.QUALITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["STAB"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/stopshield.jpg",
  },
  {
    name: "PLANKS WITH GRIP",
    type: ItemType.SHIELD,
    stats: [StatType.QUALITY, StatType.DURABILITY],
    damageTypes: ["VOLT"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/plank.png",
  },
  {
    name: "MARINE ARMOR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["BURST", "BLAST"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/armor-combat.png",
  },
  {
    name: "COMBAT ARMOR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["NUKE", "LIGHT"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/combat-armor.png",
  },
  {
    name: "BULL ARMOR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["OOZE", "NEURAL"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/poweredarmor.jpg",
  },
  {
    name: "SHELL ARMOR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["GUN", "LIGHT"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/shellarmor.png",
  },
  {
    name: "HAZMAT SUIT",
    type: ItemType.ARMOR,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "OOZE", "NUKE", "VOLT"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/hazmat.png",
  },
  {
    name: "CAMOUFLAGE",
    type: ItemType.ARMOR,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: ["*", "PAIN"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image:
      "img/items/kamouflage-och-maskering-ghillie-suit-woodland-44574-f1-removebg-preview.png",
  },
  {
    name: "ARCTIC GEAR",
    type: ItemType.ARMOR,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["*", "CUT", "SMASH"],
    hasSkill: false,
    size: ItemSize.LARGE,
    horizontal: false,
    image: "img/items/arctic.png",
  },
  {
    name: "GRAPPLER",
    type: ItemType.CYBERNETICS,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["CUT", "PAIN", "SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/grapplehand.png",
  },
  {
    name: "BIONIC ARM",
    type: ItemType.CYBERNETICS,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: ["PAIN", "SMASH"],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bionicarm.png",
  },
  {
    name: "BIONIC LEG",
    type: ItemType.CYBERNETICS,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bionicleg.png",
  },
  {
    name: "BIONIC EYE",
    type: ItemType.CYBERNETICS,
    stats: [
      StatType.QUALITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bioniceye.png",
  },
  {
    name: "POLYGEL",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/polygel.png",
  },
  {
    name: "BIO-SCANNER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/bio-scanner.png",
  },
  {
    name: "NEURO-ANIMATOR",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/neuro-animator.png",
  },
  {
    name: "GATE RECOILER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: true,
    image: "img/items/teleport-thumb-1.jpg",
  },
  {
    name: "X-RAY BEAM",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/x-ray.png",
  },
  {
    name: "SOLAR CONDENSER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/solarcondenser.png",
  },
  {
    name: "ROCKET SKATES",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/rocketskates.png",
  },
  {
    name: "FOAMCRETE DISPENSER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/foamgel.png",
  },
  {
    name: "2-DIMENSIONAL SUIT",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/2d.png",
  },
  {
    name: "MAG BOOTS",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/magboots.png",
  },
  {
    name: "ANTI-GRAV BOOTS",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/antigrav.png",
  },
  {
    name: "COPTER PACK",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/copterpack.png",
  },
  {
    name: "GROWGEL INJECTOR",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/growgel.png",
  },
  {
    name: "SLAVE CROWN",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/slavecrown.png",
  },
  {
    name: "LASER SCULPTER",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/lasersculpter.png",
  },
  {
    name: "THERMOBARIC CELL",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/thermobariccell.png",
  },
  {
    name: "AUTODOC",
    type: ItemType.ARTIFACT,
    stats: [StatType.DURABILITY, StatType.DURABILITY, StatType.DURABILITY],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/autodoc.png",
  },
  {
    name: "LIFEFORM SENSOR",
    type: ItemType.ARTIFACT,
    stats: [
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
      StatType.DURABILITY,
    ],
    damageTypes: [],
    hasSkill: false,
    size: ItemSize.SMALL,
    horizontal: false,
    image: "img/items/lifeformsensor.png",
  },
];
/*
for (var item of items) {
    item.textClass = "";
    if (item.name.length > 8) item.textClass = "small";
    if (item.name.length > 11) item.textClass = "smaller";
    if (item.name.length > 14) item.textClass = "smallest";
  }
function getItemValue(item) {
  if (item.type == "magic") return 40;
  var baseValue = item.usage.reduce((sum, usage) => getUsageValue(sum) + getUsageValue(usage));
  if (item.type == "artifact") return baseValue * 10;
  if (item.type == "cybernetics") return baseValue * 3;
  if (item.type == "stuff") return baseValue;
  if (item.type == "explosive") return baseValue;
  if (item.type == "armor") return baseValue * 2;
  return baseValue;
}
function getUsageValue(usage) {
  if (usage == StatType.DURABILITY) return 1;
  if (usage == StatType.EFFECT) return 3;
  if (usage == StatType.QUALITY) return 4;
  return usage;
}
*/
